### ISSUE TITLE
CSS not applied

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [archfirst/angular2-seed-sass#10]
I have made following file:

`src/shared/components/loader/loader.component.scss`

Somehow these css rules do not apply to main css. Is this a task/compile issue?
How could we solve this? Thank you in advance.

**Comment by asgarddesigns** [comment]
My understanding is, it will be applied at the component level using the shadow dom based off the style/styleUrls defined in the component:

@Component({
  selector: 'sd-loader',
  moduleId: module.id,
  templateUrl: './loader.component.html',
  styleUrls: ['./loader.component.css'],
...

there's a bit of relevant reading here: http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html

if it's not applying to the component when it's run, check you have specified the file as .css, not as .scss

**Comment by ZigaVukcevicDev** [comment]
@asgarddesigns thank you for pointing me out. As I have tried to write some CSS in .scss file, it is fully generation CSS to .css file.

But I am getting error: `http://localhost:5555/loader.component.css 404 (Not Found)` 
Any ideas how to fix the path issue?

**Comment by asgarddesigns** [comment]
It looks like you are either:-

a) manually linking the file in the head 

or 

b) you have set the stylesUrls incorrectly as /loader.component.css rather than ./loader.component.css (note the dot at the beginning). meaning it's looking for the file in the root directory.

**Comment by ZigaVukcevicDev** [comment]
Thank you for your reply. This is still not working although I have set it up like this:

**Component location**

```
src/shared/components/loader/loader.component.ts
```

**Code**

```
@Component({
  selector: 'loader',
  styleUrls: ['./loader.component.css'],
  template: `<div></div>`
})
```

**Error**

```
GET http://localhost:5555/loader.component.css 404 (Not Found)
EXCEPTION: Error: Uncaught (in promise): Failed to load loader.component.css
```

My component works just fine (except for the CSS). Perhaps any ideas more?

**Comment by asgarddesigns** [comment]
I am guessing you also have src/shared/components/loader/loader.component.scss as well?

Might be some sort of resolution issue...maybe look at losing the 'loader' subfolder, as it's already in the shared/components folder? 

i.e. src/shared/components/loader.component.*

**Comment by ZigaVukcevicDev** [comment]
@asgarddesigns thank you for your reply again.

Yes, I am having .scss file as well. I have tried solution without loader subfolder (have put the files in components folder) but this does not work either.

It would be nice to be able to have components also in shared folder.

**Comment by asgarddesigns** [comment]
Yep, it makes sense to be able to place in the shared folder, agreed, it was just a troubleshooting measure.

I'll try reproducing when I have a chance, but I have a new kid due in a few weeks so spare time isn't a thing right now!

**Comment by ZigaVukcevicDev** [comment]
Good luck! :)

**Comment by nareshbhatia** [comment]
@be-codified, I tried moving the `home` component to the shared folder and it works perfectly fine. Please try this and check how it is different from what you are doing:
1. Move the files from `src/home/components` to `src/shared/components/home`.
2. Delete `src/home`.
3. Modify import in `app.component.ts` to `import {HomeComponent} from '../../shared/components/home/home.component';`.
4. Modify import in `home.component.ts` to `import {NameListService} from '../../services/name-list.service';`

Now the home component should be working correctly from the shared folder. Make changes to the scss file and they should reflect correctly.

Please reopen the issue if you still can't get this to work.

P.S. As noted by @asgarddesigns, component scss applies only to the component and not globally.
