### ISSUE TITLE
Scss includePaths

### ISSUE THREAD

**Issue by DiegoYungh** [archfirst/angular2-seed-sass#12]
Guys I started using this repo yesterday and the first thing I tried to do was import foundation.

`
@import 'foundation';
`

then of course I got:

```
Error: src/assets/main.scss
Error: File to import not found or unreadable: foundation
       Parent style sheet: stdin
        on line 1 of stdin
>> @import 'foundation';
```

I went to the config looking for the SASS pipe, and found it inside _tools/tasks/seed/process.scss.ts_.

To make my import work I just had to add a well know variable called **includePaths** to the plugins.sass call, but here lies the problem:

Wouldn't it be better to have a config variable called _**sass_include_paths**_ to have all external libraries you need to compile sass and import it inside the config file ?

doesn't seem right changing inside the seed tasks folder, this sohuld be added only to the project folder or project config

what do you guys think? is there any other way to do it?

**Comment by asgarddesigns** [comment]
It probably makes sense to include it in the seed task with option to _extend_ the list of import locations in the project task... seems like something that would be worth doing and submitting as change to the seed project to me...

**Comment by DiegoYungh** [comment]
Perfect, for now I implemented here like the following:

_**seed.config.interfaces.ts**_

```
...
export interface SassOptions {
  file?: string;
  data?: string;
  importer?: (url: string, prev: string, done: (file?: string, contents?: string) => any) => any;
  functions?: Array<any>;
  includePaths?: Array<string>;
  indentedSyntax?: boolean;
  indentType?: string;
  indentWidth?: number;
  linefeed?: string;
  omitSourceMapUrl?: boolean;
  outFile?: string;
  outputStyle?: string;
  precision?: number;
  sourceComments?: boolean;
  sourceMap?: boolean;
  sourceMapContents?: boolean;
  sourceMapEmbed?: boolean;
  sourceMapRoot?: string;
}
```

**_project.config.ts_**

```
import {InjectableDependency, SassOptions} from './seed.config.interfaces';
...
let custom_sass_options: SassOptions = {
  includePaths: [
    'node_modules/foundation-sites/scss'
  ]
};
...
this.SASS_OPTIONS = Object.assign(this.SASS_OPTIONS, custom_sass_options);
...
```

**_seed.config.ts_**

```
import {InjectableDependency, Environments, SassOptions} from './seed.config.interfaces';
...
SASS_OPTIONS: SassOptions = {};
```

**_tasks/seed/process.scss.ts_**

```
import {APP_SRC, DEV_DEST, TMP_DIR, ENV, SASS_OPTIONS} from './../../config';
...
.pipe(plugins.sass(SASS_OPTIONS))
...
```

If I need more granular control over each property or merge each property I can use better functions than Object.assign

**Comment by nareshbhatia** [comment]
Hi @DiegoYungh, I have committed your suggested changes to `seed.config.interfaces.ts`, `seed.config.ts` and `build.scss.ts` (this file now replaces process.scss.ts). However, I was not able to import foundation successfully. Can you please try out this commit and let me know exactly how to import foundation?

**Comment by DiegoYungh** [comment]
Sure thing, thanks a lot for hearing my suggestion.
So after we have now a global config object we overwrite it on the project config to our taste.

Install foundation

```
npm i foundation-sites --save-dev
```

**project.config.ts**

```
let custom_sass_options: SassOptions = {
  includePaths: [
    'node_modules/foundation-sites/scss',
    ...
  ]
};

this.SASS_OPTIONS = Object.assign(this.SASS_OPTIONS, custom_sass_options);
```

Note: using Object.assign won't merge the options recursivelly, if there is any **includePaths** defined in the seed config it will be overwrited, to workaround it, we need a recursive object merge or assign it directly

```
this.SASS_OPTIONS.includePaths = Object.assign(this.SASS_OPTIONS.includePaths, custom_sass_options.includePaths);
```

Do it with the correctly existency checks or use a lodash or anyother lib function to do the merge for us, for example https://github.com/KyleAMathews/deepmerge

In your main.scss inside assets you add the foundation directive:

```
@import 'foundation';
@include foundation-grid;
```

In this case I imported **just** the grid from foundation, but you could import everything:

```
@import 'foundation';
@include foundation-everything;
```

These option you can find inside **foundation-sites** folder, after you download.
If you downloaded via bower it would be the same but changing the path from node_modules to bower_packages or your custom path.

I just uploaded a demo repo just to show it working, it is your latest commit plus my changes to add foundation.

[repository](https://github.com/DiegoYungh/angular2-seed-sass)
[change commit](https://github.com/DiegoYungh/angular2-seed-sass/commit/3c45bb57af2c51b8fb80f34e7f1a3479efdb2a03)

**Comment by nareshbhatia** [comment]
@DiegoYungh - works perfectly. Thanks for clarifying. I am going to close this issue now since the build process now supports your original suggestion.
