### ISSUE TITLE
Consider using sass-lint instead of scss-lint

### ISSUE THREAD

**Issue by Paladinium** [archfirst/angular2-seed-sass#14]
This is a feature request to replace scss-lint by sass-lint. The biggest advantage of using sass-lint is that it is a node-only solution. As far as I understand, no ruby installation and no gems are required.

This is a massive advantage when considering heterogeneous development (including the CI server) environments where installing new software is tedious.

**Comment by nareshbhatia** [comment]
I definitely like the idea of removing the ruby requirement. Let me look into this.

**Comment by nareshbhatia** [comment]
@Paladinium, scss-lint is now replaced by sass-lint. No more dependency on Ruby!

Thanks for the suggestion.

**Comment by Paladinium** [comment]
Excellent, thanks for the fix @nareshbhatia .
