### ISSUE TITLE
variables.scss global usage in component stylesheets

### ISSUE THREAD

**Issue by neekers** [archfirst/angular2-seed-sass#15]
**Description**

I want to use the variables.scss to hold global variables, but I am not allowed to reference them in component.scss files because the files aren't connected via import. 

Recommendations for a common scss file, not just "styles".

**Comment by tizot** [comment]
Same problem for me. 
In another seed, I have seen they had a `SCSS_INDEX` which was loaded first I guess...

**Comment by nareshbhatia** [comment]
You should be able to import common scss files in components. See `navbar.component.scss` as an example. It imports `_colors.scss` which is a common scss file:

```
@import '../../assets/colors';
```

Please let me know if I have misunderstood your question.
