### ISSUE TITLE
Injected css

### ISSUE THREAD

**Issue by Geoide** [archfirst/angular2-seed-sass#16]
Hi.
What is the task where you prepare the injected styles? Font-Awesome for example.... It not works in prod env after update the seed.

**Comment by nareshbhatia** [comment]
The task that takes care of the injected styles is `build.scss.ts`. The function that you want to look at is `processExternalScss()`. Currently it processes only `.scss` files, but we need to extend it to process `.css` files too - the only difference is that the `.css` files should not pass through Sass. So it is something like this:

```
function processExternalScss() {
  return gulp.src([
      join(APP_SRC, 'assets', '**', '*.scss'),  // assets/main.scss etc.
      getExternalCss().map(r => r.src)          // node_modules/.../*.css etc.
    ])
    .pipe(plugins.sass(SASS_OPTIONS))
    .pipe(isProd ? plugins.cached('process-external-css') : plugins.util.noop())
    .pipe(plugins.postcss(processors))
    .pipe(isProd ? plugins.concat(CSS_PROD_BUNDLE) : plugins.util.noop())
    .pipe(gulp.dest(CSS_DEST));
}

function getExternalCss() {
  return DEPENDENCIES.filter(d => /\.css$/.test(d.src));
}
```

Of course, this passes the css files through sass. It doesn't hurt but it's kind of a hack. Let me know if you have any suggestions.

**Comment by Geoide** [comment]
@nareshbhatia thank you very much.

Perhaps, my version would be:

```
function processExternalScss() {
  return merge(processAssetsCss(), processInjectedCss())
    .pipe(plugins.sass(SASS_OPTIONS))
    .pipe(isProd ? plugins.cached('process-external-css') : plugins.util.noop())
    .pipe(plugins.postcss(processors))
    .pipe(isProd ? plugins.concat(CSS_PROD_BUNDLE) : plugins.util.noop())
    .pipe(gulp.dest(CSS_DEST));
}

function processAssetsCss() {
  return gulp.src(join(APP_SRC, 'assets', '**', '*.scss'))
    .pipe(isProd ? plugins.cached('process-assets-css') : plugins.util.noop());
}

function processInjectedCss() {
  return gulp.src(getExternalCss().map(r => r.src))
    .pipe(isProd ? plugins.cached('process-injected-css') : plugins.util.noop());
}

function getExternalCss() {
  return DEPENDENCIES.filter(d => /\.css$/.test(d.src));
}
```

Your version not pass the typescript compile. 

```
TSError: ⨯ Unable to compile TypeScript
tools/tasks/seed/build.scss.ts (51,19): Argument of type '(string | string[])[]' is not assignable to parameter of type 'string | string[]'.
```

**Comment by nareshbhatia** [comment]
Thanks, @Geoide. I will implement something like this, though I will wait for some answers on this thread: https://github.com/mgechev/angular2-seed/pull/750.

**Comment by nareshbhatia** [comment]
@Geoide, just wanted to let you know that I will not be fixing this because I have personally switched over to [angular-cli](https://github.com/angular/angular-cli). While it is still in beta, the tool has the official support from the Angular team and has the best minds working on it. I would highly recommend that you switch over too and help the angular-cli team make that tool better.

**Comment by Geoide** [comment]
@nareshbhatia thx
