### ISSUE TITLE
Why is "assets" excluded by sass-lint?

### ISSUE THREAD

**Issue by Kunepro** [archfirst/angular2-seed-sass#18]
tools/tasks/seed/sass-lint.ts:14
Why there's a rule to specifically exclude the assets folder that is including main.scss and others (and in my opinion the best place to add mixin, patterns etc. folders).
I can easily comment out that rule, but I don't get the point of it being there in the first place…

EDIT: Actually it may be the other function trying to do that, "lintExternalCss", but it's not working as the assets/main.css is not being linted at all.

**Comment by nareshbhatia** [comment]
Good question. This needs to be cleaned up. I am waiting for some clarifications from this thread: https://github.com/mgechev/angular2-seed/pull/750.

**Comment by nareshbhatia** [comment]
@Kunepro, just wanted to let you know that I will not be fixing this issue as I have decided to switch from angular2-seed-sass to [angular-cli](https://github.com/angular/angular-cli). While it is still in beta, the tool has the official support from the Angular team and has the best minds working on it. I would highly recommend that you switch over too and help the angular-cli team make that tool better.
