### ISSUE TITLE
Process SCSS doesn't work when bringing into line with current seed version

### ISSUE THREAD

**Issue by taijuten** [archfirst/angular2-seed-sass#2]
The SCSS process appears to drop out when implementing the changes in this fork, in the up-to-date Seed repo

**Comment by nareshbhatia** [comment]
Can you please clarify the issue? I assume what you are saying is that this implementation is not tracking the original [angular2-seed](https://github.com/mgechev/angular2-seed) project. That's correct. I was tied up with another project at work and did not get a chance to sync up with the latest. Freeing up a bit now. Will get it synced up this week.

**Comment by nareshbhatia** [comment]
Thanks to Ben, the latest changes in angular2-seed have been synced to this repository.
