### ISSUE TITLE
update angular version to rc1 and other related deps update

### ISSUE THREAD

**Issue by nkmdev** [archfirst/angular2-seed-sass#20]
nice work but would be great rebuild with latest dependencies

**Comment by neekers** [comment]
+1

**Comment by thinkrapido** [comment]
+1

**Comment by nareshbhatia** [comment]
@nitinkumarmishra, @neekers, @thinkrapido, thanks for your support of angular2-seed-sass. Unfortunately I have decided to not to support this repository anymore. I have personally switched to [angular-cli](https://github.com/angular/angular-cli). While it is still in beta, the tool has the official support from the Angular team and has the best minds working on it. I would highly recommend that you switch over too and help the angular-cli team make that tool better.

**Comment by neekers** [comment]
:(  thanks for the update at least
