### ISSUE TITLE
Prod Build Failing on Build.Bundles.App

### ISSUE THREAD

**Issue by btormey** [archfirst/angular2-seed-sass#21]
**Description**
Immediately after cloning the repository and executing `npm install && npm run build.prod` the build throws the following error:

> Unhandled rejection Error on fetch for dist\tmp\main.js at file:///d:/Working/test/angular2-seed-sass/node_modules/dist\tmp\main.js
>         Error: ENOENT: no such file or directory, open 'd:\Working\test\angular2-seed-sass\node_modules\dist\tmp\main.js'
>     at Error (native)

It looks like a similar issue has been [fixed](https://github.com/mgechev/angular2-seed/issues/831) in the main angular 2 seed repository.

**Steps to Reproduce**
1. Clone repository
2. `cd angular2-seed-sass`
3. `npm install && npm run build.prod`

Current environment set up...
Windows 10
node v. 4.4.4
npm v. 3.8.1
tsc v. 1.7.5

**Comment by manish5377** [comment]
+1

**Comment by nareshbhatia** [comment]
Please note that this repository is no longer supported. See the main README file for details and alternatives.

**Comment by Priyankashelar10** [comment]
facing same issue..plz help
