### ISSUE TITLE
npm ERR! Failed at ..... --color'.

### ISSUE THREAD

**Issue by scottromack** [archfirst/angular2-seed-sass#22]
**Failed at ... --color**

npm ERR! Failed at the angular2-seed-sass@0.0.0 start script 'gulp serve.dev --color'.

**Steps to Reproduce**

I just pulled down the repo and get this error.
I see --color in many of  the angular seed projects but don't know how to chase down what it is.

I can attach the full stack trace if wanted...

**Comment by nareshbhatia** [comment]
@ShaggyDude, this repository is unsupported. Please see the notice on the home page for more information.
