### ISSUE TITLE
Prod build is broken because the global css files are not created correctly

### ISSUE THREAD

**Issue by nareshbhatia** [archfirst/angular2-seed-sass#5]
All style sheets that are not part of components need to be concatenated and output to `dist/prod/css/all.css`. See the build process in the original angular2-seed project. That process also adds the following lines to index.html which picks up the concatenated css file:

```
  <!-- inject:css -->
  <link rel="stylesheet" href="/css/all.css?1459289107856">
  <!-- endinject -->
```

**Comment by asgarddesigns** [comment]
PR #6 will fix this.

**Comment by asgarddesigns** [comment]
can this be closed now @nareshbhatia ?

**Comment by nareshbhatia** [comment]
Yes, of course :-)
