### ISSUE TITLE
prod server

### ISSUE THREAD

**Issue by dweitz43** [archfirst/angular2-seed-sass#7]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**
the production server from the original seed project was removed

**Expected/desired behavior**
searching for a recommended way to run the production build

**Other information**
i assume there is a reason that the production server was removed from this fork, just wondering if there is a suggested method of running the production build now?

**Comment by joshwiens** [comment]
@dweitz43 - Production builds have varied requirements which is why serving a prod build was pulled from the base seed.

To add a basic production 

**Add:** tools/tasks/project/serve.prod.ts

```
import {serveProd} from '../../utils';

export = serveProd
```

**Modify:** gulpfile.ts and add the following below the serve.e2e task

```
// --------------
// Serve prod
gulp.task('serve.prod', (done: any) =>
  runSequence('build.prod',
              'server.prod',
              done));
```
