### ISSUE TITLE
Enable compass in project

### ISSUE THREAD

**Issue by MichalObi** [archfirst/angular2-seed-sass#9]
I sugest to implement [compass ](http://compass-style.org/)support for this project. Many peopole who use sass would like to use their compass mixins and functions too.

In this moment when i try to use @import 'compass' it can not resolve.

I think to do this we need config.rb but i have no idea how to properly configurate it in this files structure.

In my opinion that [gulp-compass](https://www.npmjs.com/package/gulp-compass) should be implemented in gulp's task but i simply don't know when and how to do this.

Any idea how to overcome this right now ?

**Comment by asgarddesigns** [comment]
You will probably need to pipe though the compass plugin in process.scss.ts and add the gulp-compass plugin to devDependencies.

I am not too sure about importing compass, can have a bit of a look later in the week maybe.

**Comment by MichalObi** [comment]
I will be very glad for your help. I expecially would like to use Compass mixin for vendor prefixes.
I think that Autoprefixer should do the same trick, but right now it isn't working corretly for my css output.

Should i make something special to activate Autoprefixer in building app proces ?

**Comment by nareshbhatia** [comment]
Well, the autoprefixer was not being called in the correct place and with correct files. I just fixed this. Now we are tightly controlling the process of `scss` transformation so that autoprefixer is being called right after the sass preprocessor is run. Please try again and let me know if you see any issues.

**Comment by Kunepro** [comment]
Would this affect people that do not want to have compass?
I want to keep my css library minimal without external libraries of any size (even if they don't get loaded in production).

**Comment by nareshbhatia** [comment]
@Kunepro, I agree with you. Not going to add compass - if someone can document the steps to do the integration, we can happily put it on our wiki.

Since the autoprefixer part of this issue is now working, I am going to close it for now.
